const list = [
    {
        id: 1,
        title: '01. Vårrull 2stk',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SO`,
    },
    {
        id: 2,
        title: '02. Kyllingsuppe med mais',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SE, E`,
    },
    {
        id: 3,
        title: '03. Beijingsuppe (HOT)',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SO, SE, E SD`,
    },
    {
        id: 4,
        title: '04. Sprøstekte kongereker',
        category: 'forretter',
        price: "75kr",
        alergy: `GL, SD, E`,
    },
    {
        id: 5,
        title: '05. Vegetar vårrull 2stk',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SO`,
    },
    {
        id: 6,
        title: '06. Reke chips',
        category: 'forretter',
        price: "35kr",
        alergy: `SD`,
    },
    {
        id: 9,
        title: '09. Biff i rød karri og kokosmelk saus (HOT)',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SD, PN`,
    },
    {
        id: 10,
        title: '10. Biff chop suey',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 11,
        title: '11. Biff med bambusskudd i oystersaus',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 12,
        title: '12. Biff i svart peppersaus',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 13,
        title: '13. Biff i grønn karri',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE`,
    },
    {
        id: 14,
        title: '14. Biff i hvitløk chilisaus (HOT)',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE`,
    },
    {
        id: 15,
        title: '15. Pandas biff (EKSTRA HOT)',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 23,
        title: '23. Kevin spesial (HOT)',
        category: 'kylling',
        price: "189kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 24,
        title: '24. Kylling i rød karri og kokosmerlksaus (HOT)',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 25,
        title: '25. Sprøstekt kylling i appelsinsaus',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, E`,
    },
    {
        id: 26,
        title: '26. Sprøstekt kylling i sursøtsaus',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, E`,
    },
    {
        id: 27,
        title: '27. Kylling med cashew-nøtter (HOT)',
        category: 'kylling',
        price: "165kr",
        alergy: `GL, SE, SO, N`,
    },
    {
        id: 28,
        title: '28. Kylling i hvitløk chilisaus (HOT)',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, SE`,
    },
    {
        id: 29,
        title: '29. Kylling i grønn karri',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, SE`,
    },
    {
        id: 30,
        title: '30. Kylling i oystersaus',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 31,
        title: '31. Panda kylling (EKSTRA HOT)',
        category: 'kylling',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 36,
        title: '36. Sprøstekt svinekjøtt med sursøtsaus',
        category: 'svinekjøtt',
        price: "159kr",
        alergy: `GL, E`,
    },
    {
        id: 37,
        title: '37. Sprøstekt svinekjøtt med szechuansaus (HOT)',
        category: 'svinekjøtt',
        price: "159kr",
        alergy: `GL, E, SE, SO`,
    },
    {
        id: 38,
        title: '38. Sprøstekt svinekjøtt med grønn karrisaus',
        category: 'svinekjøtt',
        price: "159kr",
        alergy: `GL, SE, E`,
    },
    {
        id: 45,
        title: '45. Kongereker i rød karri & kokosmelksaus (HOT)',
        category: 'kongereker',
        price: "189kr",
        alergy: `GL, SD, PN`,
    },
    {
        id: 46,
        title: '46. Sprøstekte kongereker med sursøtsaus',
        category: 'kongereker',
        price: "189kr",
        alergy: `GL, E, SD`,
    },
    {
        id: 47,
        title: '47. Kongereker med chashew-nøtter (HOT)',
        category: 'kongereker',
        price: "195kr",
        alergy: `GL, SD, SE, SO, N`,
    },
    {
        id: 48,
        title: '48. Pandas kongereker (EKSTRA HOT)',
        category: 'kongereker',
        price: "189kr",
        alergy: `GL, SE, SO, SD`,
    },
    {
        id: 49,
        title: '49. Kongereker i hvitløk chilisaus (HOT)',
        category: 'kongereker',
        price: "189kr",
        alergy: `GL, SE, SD`,
    },
    {
        id: 66,
        title: '66. Sprøstekt and med sursøtsaus',
        category: 'and',
        price: "199kr",
        alergy: `GL, E`,
    },
    {
        id: 67,
        title: '67. Sprøstekt and med appelsinsaus',
        category: 'and',
        price: "199kr",
        alergy: `GL, E`,
    },
    {
        id: 70,
        title: '70. Stekt ris med biff og egg',
        category: 'stekt ris',
        price: "159kr",
        alergy: `GL, SE, E, SO`,
    },
    {
        id: 71,
        title: '71. Stekt ris med kylling og egg',
        category: 'stekt ris',
        price: "159kr",
        alergy: `GL, SE, E, SO`,
    },
    {
        id: 72,
        title: '72. Stekte nudler med kylling i soyasaus',
        category: 'stekte nudler',
        price: "159kr",
        alergy: `GL, SE, E, SO`,
    },
    {
        id: 73,
        title: '73. Stekte nudler med biff i soyasaus',
        category: 'stekte nudler',
        price: "159kr",
        alergy: `GL, SE, E, SO`,
    },
    {
        id: 74,
        title: '74. Stekte nudler med kongereker i soyasaus',
        category: 'stekte nudler',
        price: "189kr",
        alergy: `GL, SD, SE, E, SO`,
    },
    {
        id: 75,
        title: '75. Tjo & Hei (HOT HOT)',
        category: 'stekte nudler',
        price: "169kr",
        alergy: `GL, SE, E, SO`,
    },
    {
        id: 77,
        title: '77. Grillet kylling med salat og pommes frites',
        category: 'grillmeny',
        price: "159kr",
        alergy: ``,
    },
    {
        id: 78,
        title: '78. Pølse med pommes frites',
        category: 'barnemeny',
        price: "69kr",
        alergy: ``,
    },
    {
        id: 79,
        title: '79. Kylling med pommes frites',
        category: 'barnemeny',
        price: "69kr",
        alergy: ``,
    },
    {
        id: 80,
        title: '80. Pommes frites',
        category: 'barnemeny',
        price: "49kr",
        alergy: ``,
    },
    {
        id: 90,
        title: '90. Lammefilet i hvitløk chilisaus (HOT)',
        category: 'gourmetretter',
        price: "199kr",
        alergy: `GL, SE`,
    },
    {
        id: 91,
        title: '91. Indrefilet med sterk kinesisk chilisaus (HOT)',
        category: 'gourmetretter',
        price: "199kr",
        alergy: `GL, SE`,
    },
    {
        id: 92,
        title: '92. Indrefilet i svart peppersaus',
        category: 'gourmetretter',
        price: "199kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 93,
        title: '93. Woket and i szechuansaus (HOT)',
        category: 'gourmetretter',
        price: "199kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 100,
        title: 'Ris',
        category: 'ekstra',
        price: "20kr",
        alergy: ``,
    },
    {
        id: 101,
        title: 'Kylling, Biff & Svinekjøtt',
        category: 'ekstra',
        price: "45kr",
        alergy: ``,
    },
    {
        id: 102,
        title: 'Kongereker, And & Gourmet kjøtt',
        category: 'ekstra',
        price: "65kr",
        alergy: ``,
    },
];

export default list;