const list = [
    {
        id: 1,
        title: '01. Vårrull 2stk',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SO`,
    },
    {
        id: 2,
        title: '02. Kyllingsuppe med mais',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SE, E`,
    },
    {
        id: 3,
        title: '03. Beijingsuppe(HOT)',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SO, SE, E SD`,
    },
    {
        id: 4,
        title: '04. Sprøstekte kongereker',
        category: 'forretter',
        price: "75kr",
        alergy: `GL, SD, E`,
    },
    {
        id: 5,
        title: '05. Vegetar vårrull 2stk',
        category: 'forretter',
        price: "59kr",
        alergy: `GL, SO`,
    },
    {
        id: 6,
        title: '06. Reke chips',
        category: 'forretter',
        price: "35kr",
        alergy: `SD`,
    },
    {
        id: 9,
        title: '09. Biff i rød karri og kokosmelk saus()HOT',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SD, PN`,
    },
    {
        id: 10,
        title: '10. Biff chop suey',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 11,
        title: '11. Biff med bambusskudd i oystersaus',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 12,
        title: '12. Biff i svart peppersaus',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 13,
        title: '13. Biff i grønn karri',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE`,
    },
    {
        id: 14,
        title: '14. Biff i hvitløk chilisaus(HOT)',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE`,
    },
    {
        id: 15,
        title: '15. Pandas biff(EKSTRA HOT)',
        category: 'biff',
        price: "159kr",
        alergy: `GL, SE, SO`,
    },
    {
        id: 0,
        title: '',
        category: 'biff',
        price: 16.99,
        alergy: ``,
    },
];

export default list;